from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class SameHeartTeamAssets: 


	# Click Rule Assets
	# 觉醒副本，集结 
	C_I_SAME_HEART_TEAM_GATHER_CHOOSE = RuleClick(roi_front=(399,470,485,70), roi_back=(399,470,485,70), name="i_same_heart_team_gather_choose")


	# Image Rule Assets
	# 同心队页面的--集结图标 
	I_I_SAME_HEART_TEAM_GATHER = RuleImage(roi_front=(1095,621,85,60), roi_back=(1052,544,228,176), threshold=0.8, method="Template matching", file="./tasks/SameHeartTeam/res/res_i_same_heart_team_gather.png")
	# 未选中状态 
	I_I_GATHER_UNSELECTED = RuleImage(roi_front=(463,255,16,16), roi_back=(418,242,462,41), threshold=0.5, method="Template matching", file="./tasks/SameHeartTeam/res/res_i_gather_unselected.png")
	# 被选中状态 
	I_I_GATHER_SELECTED = RuleImage(roi_front=(558,255,16,16), roi_back=(418,242,462,41), threshold=0.8, method="Template matching", file="./tasks/SameHeartTeam/res/res_i_gather_selected.png")
	# 同心队的组队按钮 
	I_I_SAME_HEART_TEAM_UP = RuleImage(roi_front=(969,637,56,54), roi_back=(897,567,383,153), threshold=0.8, method="Template matching", file="./tasks/SameHeartTeam/res/res_i_same_heart_team_up.png")
	# 解散同心队图标 
	I_I_SAME_HEART_TEAM_CLOSE = RuleImage(roi_front=(742,34,42,40), roi_back=(636,0,309,99), threshold=0.8, method="Template matching", file="./tasks/SameHeartTeam/res/res_i_same_heart_team_close.png")
	# 同心队入口标志 
	I_I_SAME_HEART_TEAM_ENTER = RuleImage(roi_front=(32,585,82,65), roi_back=(0,494,412,226), threshold=0.8, method="Template matching", file="./tasks/SameHeartTeam/res/res_i_same_heart_team_enter.png")
	# 觉醒副本，集结！ 
	I_I_SAME_HEART_TEAM_GATHER_CHOOSE3 = RuleImage(roi_front=(410,480,464,48), roi_back=(393,471,495,72), threshold=0.8, method="Template matching", file="./tasks/SameHeartTeam/res/res_i_same_heart_team_gather_choose3.png")
	# 探索副本，集结！ 
	I_I_SAME_HEART_TEAM_GATHER_CHOOSE2 = RuleImage(roi_front=(413,399,464,48), roi_back=(393,384,496,77), threshold=0.8, method="Template matching", file="./tasks/SameHeartTeam/res/res_i_same_heart_team_gather_choose2.png")
	# 御魂副本，集结！ 
	I_I_SAME_HEART_TEAM_GATHER_CHOOSE1 = RuleImage(roi_front=(414,318,464,48), roi_back=(393,303,502,75), threshold=0.8, method="Template matching", file="./tasks/SameHeartTeam/res/res_i_same_heart_team_gather_choose1.png")


	# Ocr Rule Assets
	# 同心队页面左上角同心队 
	O_O_SAMEHEARTTEAM = RuleOcr(roi=(0,0,240,70), area=(0,0,240,70), mode="Full", method="Default", keyword="", name="o_sameheartteam")


