from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class FrogBossAssets: 


	# Image Rule Assets
	# 左边竞猜 
	I_BET_LEFT = RuleImage(roi_front=(271,297,145,100), roi_back=(104,256,454,254), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_bet_left.png")
	# 右边竞猜 
	I_BET_RIGHT = RuleImage(roi_front=(1072,301,146,100), roi_back=(1012,268,255,211), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_bet_right.png")
	# description 
	I_BET_SUCCESS_BOX = RuleImage(roi_front=(710,399,87,50), roi_back=(514,368,377,144), threshold=0.75, method="Template matching", file="./tasks/FrogBoss/fb/fb_bet_success_box.png")
	# 左边赢了 
	I_SUCCESS_LEFT = RuleImage(roi_front=(297,303,100,100), roi_back=(248,268,202,221), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_success_left.png")
	# 右边输了 
	I_FAILURE_RIGHT = RuleImage(roi_front=(1099,296,100,100), roi_back=(993,242,224,199), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_failure_right.png")
	# description 
	I_NEXT_COMPETITION = RuleImage(roi_front=(673,510,42,36), roi_back=(658,449,193,137), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_next_competition.png")
	# 30万金币 
	I_GOLD_30 = RuleImage(roi_front=(858,494,78,76), roi_back=(809,427,147,187), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_gold_30.png")
	# 确认竞猜 
	I_BET_SURE = RuleImage(roi_front=(1025,402,100,100), roi_back=(1000,297,200,226), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_bet_sure.png")
	# description 
	I_GOLD_30_CHECK = RuleImage(roi_front=(513,196,58,53), roi_back=(402,141,459,489), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_gold_30_check.png")
	# description 
	I_BETTED = RuleImage(roi_front=(275,309,125,54), roi_back=(49,283,1192,161), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_betted.png")
	# description 
	I_SUCCESS_RIGHT = RuleImage(roi_front=(1048,341,122,116), roi_back=(999,243,201,260), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_success_right.png")
	# description 
	I_FAILURE_LEFT = RuleImage(roi_front=(116,307,100,100), roi_back=(241,265,193,219), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_failure_left.png")
	# description 
	I_BET_FAILURE = RuleImage(roi_front=(625,276,269,72), roi_back=(433,214,601,183), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_bet_failure.png")
	# description 
	I_BET_SUCCESS = RuleImage(roi_front=(630,275,260,73), roi_back=(433,214,601,183), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_bet_success.png")


	# Image Rule Assets
	# description 
	I_FROG_BOSS_ENTER = RuleImage(roi_front=(1191,391,36,38), roi_back=(1174,135,78,320), threshold=0.7, method="Template matching", file="./tasks/FrogBoss/fb/fb_frog_boss_enter.png")
	# 休息中 
	I_FROG_BOSS_REST = RuleImage(roi_front=(510,274,169,64), roi_back=(492,260,516,322), threshold=0.8, method="Template matching", file="./tasks/FrogBoss/fb/fb_frog_boss_rest.png")


	# Ocr Rule Assets
	# Ocr-description 
	O_LEFT_COUNT = RuleOcr(roi=(292,468,153,33), area=(292,468,153,33), mode="Digit", method="Default", keyword="", name="left_count")
	# Ocr-description 
	O_RIGHT_COUNT = RuleOcr(roi=(1109,470,148,34), area=(1109,470,148,34), mode="Digit", method="Default", keyword="", name="right_count")
	# Ocr-description 
	O_TIME_REMAIN = RuleOcr(roi=(687,527,137,48), area=(687,527,137,48), mode="Duration", method="Default", keyword="", name="time_remain")


