from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class OrochiAssets:


	# Image Rule Assets
	# 八级大蛇进入
	I_OROCHI = RuleImage(roi_front=(279,278,47,60), roi_back=(57,120,293,403), threshold=0.8, method="Template matching", file="./tasks/Orochi/o/o_orochi.png")
	# 组队
	I_FORM_TEAM = RuleImage(roi_front=(960,594,98,70), roi_back=(913,547,193,166), threshold=0.8, method="Template matching", file="./tasks/Orochi/o/o_form_team.png")
	# 锁定
	I_OROCHI_LOCK = RuleImage(roi_front=(704,658,22,26), roi_back=(623,645,270,64), threshold=0.6, method="Template matching", file="./tasks/Orochi/o/o_orochi_lock.png")
	# 解锁
	I_OROCHI_UNLOCK = RuleImage(roi_front=(705,658,19,23), roi_back=(623,649,273,59), threshold=0.6, method="Template matching", file="./tasks/Orochi/o/o_orochi_unlock.png")
	# 点击挑战
	I_OROCHI_FIRE = RuleImage(roi_front=(1145,594,94,49), roi_back=(1123,572,131,124), threshold=0.6, method="Template matching", file="./tasks/Orochi/o/o_orochi_fire.png")
	# 式神录
	I_SHI_RECORDS = RuleImage(roi_front=(843,568,44,44), roi_back=(615,523,333,197), threshold=0.8, method="Template matching", file="./tasks/Orochi/o/o_shi_records.png")
	# 小小宠物，发现宝藏
	I_PET_PRESENT = RuleImage(roi_front=(873,184,62,147), roi_back=(873,184,62,147), threshold=0.8, method="Template matching", file="./tasks/Orochi/o/o_pet_present.png")
	# 八岐大蛇标志
	I_OROCHI_CHECK_10 = RuleImage(roi_front=(929,123,203,39), roi_back=(896,100,269,84), threshold=0.8, method="Template matching", file="./tasks/Orochi/o/o_orochi_check_10.png")
	# 巫女大蛇标志
	I_OROCHI_CHECK_11 = RuleImage(roi_front=(929,123,203,39), roi_back=(896,100,269,84), threshold=0.8, method="Template matching", file="./tasks/Orochi/o/o_orochi_check_11.png")
	# 神罚标志
	I_OROCHI_CHECK_12 = RuleImage(roi_front=(929,116,100,46), roi_back=(896,100,269,84), threshold=0.8, method="Template matching", file="./tasks/Orochi/o/o_orochi_check_12.png")
	# 虚无大蛇标志
	I_OROCHI_CHECK_13 = RuleImage(roi_front=(929,121,211,41), roi_back=(896,100,269,84), threshold=0.8, method="Template matching", file="./tasks/Orochi/o/o_orochi_check_13.png")


	# List Rule Assets
	# 这个是御魂界面选择不同层数的
	L_LAYER_LIST = RuleList(folder="./tasks/Orochi/res", direction="vertical", mode="ocr", roi_back=(127,95,106,603), size=(106, 101),
					 array=["壹", "贰", "叁", "肆", "伍", "陆", "柒", "捌", "玖", "拾", "悲", "神", "虚"])


	# Ocr Rule Assets
	# Ocr-description
	O_O_TEST_OCR = RuleOcr(roi=(126,136,360,491), area=(126,136,360,491), mode="Full", method="Default", keyword="", name="o_test_ocr")


	# Click Rule Assets
	# 单人战斗结算上面随机点
	C_ALONE_RESULT_WIN_RANDOM_TOP = RuleClick(roi_front=(15,12,813,45), roi_back=(118,12,710,45), name="alone_result_win_random_top")
	# 单人战斗结算下面随机点
	C_ALONE_RESULT_WIN_RANDOM_BOTTOM = RuleClick(roi_front=(450,547,810,160), roi_back=(118,12,710,45), name="alone_result_win_random_bottom")
	# 单人战斗结算中间随机点
	C_ALONE_RESULT_WIN_RANDOM_CENTER = RuleClick(roi_front=(150,57,1000,490), roi_back=(10,110,1260,510), name="alone_result_win_random_center")
	# 单人战斗结算左边随机点
	C_ALONE_RESULT_WIN_RANDOM_LEFT = RuleClick(roi_front=(15,57,125,650), roi_back=(15,57,125,650), name="alone_result_win_random_left")
	# 单人战斗结算右边随机点
	C_ALONE_RESULT_WIN_RANDOM_RIGHT = RuleClick(roi_front=(462,57,808,490), roi_back=(608,110,662,600), name="alone_result_win_random_right")
	# 组队战斗结算上面随机点
	C_TEAM_RESULT_WIN_RANDOM_TOP = RuleClick(roi_front=(125,10,700,90), roi_back=(10,110,1260,510), name="team_result_win_random_top")
	# 组队战斗结算下面随机点
	C_TEAM_RESULT_WIN_RANDOM_BOTTOM = RuleClick(roi_front=(462,605,800,100), roi_back=(608,110,662,600), name="team_result_win_random_bottom")
	# 组队战斗结算中间随机点
	C_TEAM_RESULT_WIN_RANDOM_CENTER = RuleClick(roi_front=(420,100,448,280), roi_back=(608,110,662,600), name="team_result_win_random_center")
	# 组队战斗结算左边随机点
	C_TEAM_RESULT_WIN_RANDOM_LEFT = RuleClick(roi_front=(10,100,410,530), roi_back=(10,100,130,610), name="team_result_win_random_left")
	# 组队战斗结算右边随机点
	C_TEAM_RESULT_WIN_RANDOM_RIGHT = RuleClick(roi_front=(868,48,402,662), roi_back=(608,110,662,600), name="team_result_win_random_right")
	# 通用奖励左边随机点
	C_REWARD_RANDOM_LEFT = RuleClick(roi_front=(12,109,81,510), roi_back=(608,110,662,600), name="reward_random_left")
	# 通用奖励右边随机点
	C_REWARD_RANDOM_RIGHT = RuleClick(roi_front=(1185,150,85,550), roi_back=(608,110,662,600), name="reward_random_right")
	# 通用奖励下边随机点
	C_REWARD_RANDOM_DOWN = RuleClick(roi_front=(462,599,800,100), roi_back=(608,110,662,600), name="reward_random_down")
	# 通用奖励上边随机点
	C_REWARD_RANDOM_TOP = RuleClick(roi_front=(180,58,650,90), roi_back=(608,110,662,600), name="reward_random_top")


